#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import click

from gitcommit.codeparser.codeparser import CodeParser

# from gitcommit import __version__

__author__ = "Giovanni Colapinto"
__copyright__ = "Giovanni Colapinto"
__license__ = "mit"

_logger = logging.getLogger("gitcommit")


def setup_logging(loglevel):
    """Setup basic logging

    Args:
      loglevel (int): minimum loglevel for emitting messages
    """
    global _logger
    handler_console = logging.StreamHandler()
    formatter_base = logging.Formatter(
        "%(asctime)s|%(levelname)s|%(name)s|%(module)s|%(lineno)s|%(message)s"
    )
    handler_console.setFormatter(formatter_base)
    level = logging.getLevelName(loglevel)
    _logger.setLevel(level)
    _logger.addHandler(handler_console)


@click.command()
@click.argument("path")
@click.option("--log-level", default="DEBUG", help="Desired log level")
@click.option("--debug/--no-debug", "-d", default=False, help="Debug mode")
@click.option("--dry-run/--no-dry-run", default=False, help="Do not overwrite files")
@click.option(
    "--untracked/--no-untracked", default=False, help="Parse also untracked files"
)
@click.option("--comment", "-c", default="#", help="Comment char")
@click.option(
    "--summary",
    "-s",
    default="Autogenerated by gitcommit",
    help="Commit comment summary (it will be trunked at 50 chars)",
)
@click.option(
    "--mark", "-m", default="->", help="Chars after comment to identify gitcomment mark"
)
def main(
    path: str,
    log_level: str,
    comment: str,
    mark: str,
    debug: bool,
    dry_run: bool,
    untracked: bool,
    summary: str,
):
    """Create git commit message from comments in code"""
    setup_logging(log_level)

    parser = CodeParser(
        path=path,
        comment=comment,
        mark=mark,
        dry_run=dry_run,
        debug=debug,
        untracked=untracked,
        summary=summary,
    )

    message_file_name = "unknown"
    try:
        message_file_name = parser.run()
    except Exception as e:
        _logger.error(f"Something went wrong during code parser. Error: {e}")

    print(message_file_name)


if __name__ == "__main__":
    main()
